-- ユーザテーブル作成
CREATE TABLE IF NOT EXISTS projects
(
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    client VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    amount INT NOT NULL DEFAULT 0,
    start_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    end_at DATETIME ON UPDATE CURRENT_TIMESTAMP,
    is_deleted TINYINT NOT NULL DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS assigns
(
    id INT NOT NULL AUTO_INCREMENT,
    projects_id INT NOT NULL,
    members_id INT NOT NULL,
    is_deleted TINYINT NOT NULL DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS members
(
    id INT NOT NULL AUTO_INCREMENT,
    number INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    is_deleted TINYINT NOT NULL DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
) ENGINE=InnoDB